name: "units-test"
on:
  project_card:
    types: [moved]

jobs:
  # test action works running from the graph  
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      id: project_column
    - run: echo ${{steps.project_column.column_name}}
